### ISSUE TITLE
Not found in raycast store

### ISSUE THREAD

**Issue by DDDOH** [zhuozhiyongde/SimpleTexOCR#1]
Thanks for this fantastic extension. But I cannot find it on raycast store.

**Comment by zhuozhiyongde** [comment]
Sorry, my PR is still has some problem, I think I will fix it this weekend
See https://github.com/raycast/extensions/pull/8500#issuecomment-1764194404

**Comment by DDDOH** [comment]
Thanks a lot. Really in need of this extension.

**Comment by zhuozhiyongde** [comment]
Fixed https://github.com/raycast/extensions/pull/8500
Now you can download this extension in Raycast store.

**Comment by DDDOH** [comment]
Thanks! It is really convenient to use Raycast for this OCR task.

On Oct 23, 2023, at 08:16, Arthals ***@***.***> wrote:



Fixed raycast/extensions#8500<https://github.com/raycast/extensions/pull/8500>
Now you can download this extension in Raycast store.
